export const TYPES = {
  IngredientsRepository: Symbol.for("IngredientsRepository"),
  ManageIngredientsUseCase: Symbol.for("ManageIngredientsUseCase"),
  TranslationService: Symbol.for("TranslationService"),
  SuggestRecipesRepository: Symbol.for("SuggestRecipesRepository"),
  SuggestRecipesUseCase: Symbol.for("SuggestRecipesUseCase"),
  SpoonacularApi: Symbol.for("SpoonacularApi"),
  ConfigService: Symbol.for("ConfigService"),
  KeyValueStorage: Symbol.for("KeyValueStorage"),
  SecureKeyValueStorage: Symbol.for("SecureKeyValueStorage"),
  GetDetailsApi: Symbol.for("GetDetailsApi"),
  RecipesDetailsRepository: Symbol.for("RecipesDetailsRepository"),
  RecipesDetailsUseCase: Symbol.for("RecipesDetailsUseCase"),
  SpoonacularMapper: Symbol.for("SpoonacularMapper"),
};
